config/routes.rb
Rails.application.routes.draw do
  resources :documents
  resources :engines
  resources :brands
  resources :cars
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "brands#index"
end

app/models/document.rb
class Document < ApplicationRecord
  validates :code, :car_id, presence: true
  belongs_to :car, dependent: :destroy
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  include Authorization
  before_action :set_document, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :authorize_admin!, except: [:index, :show]

  # GET /documents or /documents.json
  def index
    @documents = Document.all
  end

  # GET /documents/1 or /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents or /documents.json
  def create
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to document_url(@document), notice: "Document was successfully created." }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1 or /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to document_url(@document), notice: "Document was successfully updated." }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1 or /documents/1.json
  def destroy
    @document.destroy

    respond_to do |format|
      format.html { redirect_to documents_url, notice: "Document was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_document
    @document = Document.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def document_params
    params.require(:document).permit(:car_id, :code)
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_document.html.erb
<div id="<%= dom_id document %>">
  <p>
    <strong>Car:</strong>
    <%= document.car_id %>
  </p>

  <p>
    <strong>Code:</strong>
    <%= document.code %>
  </p>

</div>

app/views/documents/_form.html.erb
<%= form_with(model: document) do |form| %>
  <% if document.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
        <% document.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :car_id, style: "display: block" %>
    <%= form.text_field :car_id %>
  </div>

  <div>
    <%= form.label :code, style: "display: block" %>
    <%= form.text_field :code %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
            crossorigin="anonymous"
        />
        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
            crossorigin="anonymous"
        ></script>
    </head>
    <body class="bg-dark-subtle min-vh-100 d-flex flex-column">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid justify-content-start">
                <button
                    class="navbar-toggler"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarNav"
                    aria-controls="navbarNav"
                    aria-expanded="false"
                    aria-label="Toggle navigation"
                >
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand ps-4" href="#">T5</a>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <% if current_user %>
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="<%= brands_path %>">Brands</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<%= cars_path %>">Cars</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<%= engines_path %>">Engines</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<%= documents_path %>">Documents</a>
                            </li>
                            <%= button_to(
                                "Log Out",
                                destroy_user_session_path,
                                method: :delete,
                                class:  "nav-link"
                            ) %>
                        <% else %>
                            <li class="nav-item">
                                <a class="nav-link" href="<%= new_user_session_path %>">Sign in</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<%= new_user_registration_path %>">Sign up</a>
                            </li>
                        <% end %>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container d-flex flex-column flex-grow-1 align-items-center justify-content-center">
            <h1>Editing document</h1>
            <p id="document-help" class="text-decoration-underline mb-1">Help<p>
            <%= form_with(model: @document, html: { class: 'bg-dark rounded-4 text-white p-4 justify-content-center text-center' }) do |form| %>
                <div class="mb-3">
                    <%= form.label :code, class: 'form-label', style: "display: block" %>
                    <%= form.text_field :code, class: 'form-control' %>
                </div>

                <div class="mb-3">
                    <%= form.label :car_id, class: 'form-label', style: "display: block" %>
                    <%= form.collection_select :car_id, Car.left_outer_joins(:document).where(documents: { id: nil }) + [@document.car].compact, :id, :model, {}, class: 'form-select' %>
                </div>

                <div>
                    <%= form.submit "Edit document", class: 'btn btn-warning' %>
                </div>
                <% if @document.errors.any? %>
                    <div class="mt-3">
                        <% @document.errors.full_messages.each do |message| %>
                            <span class="text-danger"><%= message %></span><br />
                        <% end %>
                    </div>
                <% end %>
            <% end %>
            <a class="mt-3" href="<%= document_path(@document) %>">Return to document</a>
        </div>

        <script>
            var helpDocumentButton = document.getElementById('document-help');
                helpDocumentButton.addEventListener('click', function() {
                alert("Fill in the fields with an eight-character code and the car to which the document belongs (if there is no option, there is no car without documents in the database).");
            });
        </script>
    </body>
</html>

app/views/documents/index.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
            crossorigin="anonymous"
        />

        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
            crossorigin="anonymous"
        ></script>
    </head>
    <body class="bg-dark-subtle min-vh-100 d-flex flex-column">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid justify-content-start">
                <button
                    class="navbar-toggler"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarNav"
                    aria-controls="navbarNav"
                    aria-expanded="false"
                    aria-label="Toggle navigation"
                >
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand ps-4" href="#">T5</a>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <% if current_user %>
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="<%= brands_path %>">Brands</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<%= cars_path %>">Cars</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<%= engines_path %>">Engines</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" href="<%= documents_path %>">Documents</a>
                            </li>
                            <%= button_to(
                                "Log Out",
                                destroy_user_session_path,
                                method: :delete,
                                class:  "nav-link"
                            ) %>
                        <% else %>
                            <li class="nav-item">
                                <a class="nav-link" href="<%= new_user_session_path %>">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<%= new_user_registration_path %>">Signup</a>
                            </li>
                        <% end %>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container d-flex flex-column flex-grow-1 align-items-center justify-content-center">
            <% if @documents.any? %>
            <h1>Your documents</h1>
            <table class="table my-4 rounded-4 table-dark overflow-hidden text-center">
                <thead>
                    <tr>
                        <th scope="col">Document</th>
                        <th scope="col">View</th>
                        <% if current_user.admin? %>
                            <th scope="col">Edit</th>
                            <th scope="col">Delete</th>
                        <% end %>
                    </tr>
                </thead>
                <tbody>
                    <% @documents.each do |document| %>
                        <tr>
                            <td><%= document.code %></td>
                            <td>
                                <a href="<%=document_path(document)%>" class="btn btn-primary">
                                    <svg
                                        xmlns="http://www.w3.org/2000/svg"
                                        width="16"
                                        height="16"
                                        fill="currentColor"
                                        class="bi bi-eye-fill"
                                        viewBox="0 0 16 16"
                                    >
                                        <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z" />
                                        <path d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z" />
                                    </svg>
                                </a>
                            </td>
                            <% if current_user.admin? %>
                                <td>
                                    <a href="<%=edit_document_path(document)%>" class="btn btn-warning">
                                        <svg
                                            xmlns="http://www.w3.org/2000/svg"
                                            width="16"
                                            height="16"
                                            fill="currentColor"
                                            class="bi bi-pencil-fill"
                                            viewBox="0 0 16 16"
                                        >
                                            <path
                                                d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"
                                            />
                                        </svg>
                                    </a>
                                </td>
                                <td>
                                    <%= button_to document_path(document), method: :delete, data: { confirm: "Are you sure you want to delete this document?" }, class: "btn btn-danger" do %>
                                        <svg
                                            xmlns="http://www.w3.org/2000/svg"
                                            width="16"
                                            height="16"
                                            fill="currentColor"
                                            class="bi bi-trash3-fill"
                                            viewBox="0 0 16 16"
                                        >
                                            <path
                                                d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5Zm-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5ZM4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06Zm6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528ZM8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5Z"
                                            />
                                        </svg>
                                    <% end %>
                                </td>
                            <% end %>
                        </tr>
                    <% end %>
                </tbody>
            </table>
            <% else %>
                <h1 class="text-center">No documents found</h1>
            <% end %>
            <%
                if current_user.admin?
                    %>
                        <a href="<%= new_document_path %>" class="btn btn-primary">Add new document</a>
                    <%
                end
            %>
        </div>
    </body>
</html>

app/views/documents/new.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
            crossorigin="anonymous"
        />
        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
            crossorigin="anonymous"
        ></script>
    </head>
    <body class="bg-dark-subtle min-vh-100 d-flex flex-column">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid justify-content-start">
                <button
                    class="navbar-toggler"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarNav"
                    aria-controls="navbarNav"
                    aria-expanded="false"
                    aria-label="Toggle navigation"
                >
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand ps-4" href="#">T5</a>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <% if current_user %>
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="<%= brands_path %>">Brands</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<%= cars_path %>">Cars</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<%= engines_path %>">Engines</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<%= documents_path %>">Documents</a>
                            </li>
                            <%= button_to(
                                "Log Out",
                                destroy_user_session_path,
                                method: :delete,
                                class:  "nav-link"
                            ) %>
                        <% else %>
                            <li class="nav-item">
                                <a class="nav-link" href="<%= new_user_session_path %>">Sign in</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<%= new_user_registration_path %>">Sign up</a>
                            </li>
                        <% end %>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container d-flex flex-column flex-grow-1 align-items-center justify-content-center">
            <h1>New document</h1>
            <p id="document-help" class="text-decoration-underline mb-1">Help<p>
            <%= form_with(model: @document, html: { class: 'bg-dark rounded-4 text-white p-4 justify-content-center text-center' }) do |form| %>
                <div class="mb-3">
                    <%= form.label :code, class: 'form-label', style: "display: block" %>
                    <%= form.text_field :code, class: 'form-control' %>
                </div>

                <div class="mb-3">
                    <%= form.label :car_id, "Car", class: 'form-label', style: "display: block" %>
                    <%= form.collection_select :car_id, Car.left_outer_joins(:document).where(documents: { id: nil }), :id, :model, {}, class: 'form-select' %>
                </div>

                <div>
                    <%= form.submit "Create document", class: 'btn btn-primary' %>
                </div>
                <% if @document.errors.any? %>
                    <div class="mt-3">
                        <% @document.errors.full_messages.each do |message| %>
                            <span class="text-danger"><%= message %></span><br />
                        <% end %>
                    </div>
                <% end %>
            <% end %>
        </div>

        <script>
            var helpDocumentButton = document.getElementById('document-help');
                helpDocumentButton.addEventListener('click', function() {
                alert("Fill in the fields with an eight-character code and the car to which the document belongs (if there is no option, there is no car without documents in the database).");
            });
        </script>
    </body>
</html>

app/views/documents/show.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
            crossorigin="anonymous"
        />

        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
            crossorigin="anonymous"
        ></script>
    </head>
    <body class="bg-dark-subtle min-vh-100 d-flex flex-column">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid justify-content-start">
                <button
                    class="navbar-toggler"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarNav"
                    aria-controls="navbarNav"
                    aria-expanded="false"
                    aria-label="Toggle navigation"
                >
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand ps-4" href="#">T5</a>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <% if current_user %>
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="<%= brands_path %>">Brands</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<%= cars_path %>">Cars</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<%= engines_path %>">Engines</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<%= documents_path %>">Documents</a>
                            </li>
                            <%= button_to(
                                "Log Out",
                                destroy_user_session_path,
                                method: :delete,
                                class:  "nav-link"
                            ) %>
                        <% else %>
                            <li class="nav-item">
                                <a class="nav-link" href="<%= new_user_session_path %>">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<%= new_user_registration_path %>">Signup</a>
                            </li>
                        <% end %>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container d-flex flex-column flex-grow-1 align-items-center justify-content-center">
            <h1>Document <%= @document.code %></h1>
            <table class="table my-4 rounded-4 table-dark overflow-hidden text-center">
                <thead>
                    <tr>
                        <th scope="col">Code</th>
                        <th scope="col">Car</th>
                        <% if current_user.admin? %>
                            <th scope="col">Edit</th>
                            <th scope="col">Delete</th>
                        <% end %>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><%= @document.code %></td>
                        <td><%= link_to @document.car.model, car_path(@document.car) %></td>
                        <% if current_user.admin? %>
                            <td>
                                <a href="<%=edit_document_path(@document)%>" class="btn btn-warning">
                                    <svg
                                        xmlns="http://www.w3.org/2000/svg"
                                        width="16"
                                        height="16"
                                        fill="currentColor"
                                        class="bi bi-pencil-fill"
                                        viewBox="0 0 16 16"
                                    >
                                        <path
                                            d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"
                                        />
                                    </svg>
                                </a>
                            </td>
                            <td>
                                <%= button_to document_path(@document), method: :delete, data: { confirm: "Are you sure you want to delete this document?" }, class: "btn btn-danger" do %>
                                    <svg
                                        xmlns="http://www.w3.org/2000/svg"
                                        width="16"
                                        height="16"
                                        fill="currentColor"
                                        class="bi bi-trash3-fill"
                                        viewBox="0 0 16 16"
                                    >
                                        <path
                                            d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5Zm-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5ZM4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06Zm6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528ZM8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5Z"
                                        />
                                    </svg>
                                <% end %>
                            </td>
                        <% end %>
                    </tr>
                </tbody>
            </table>
        </div>
    </body>
</html>