config/routes.rb
Rails.application.routes.draw do
  resources :documents
  resources :engines
  resources :brands
  resources :cars
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "brands#index"
end

app/models/car.rb
class Car < ApplicationRecord
  validates :model, :brand_id, presence: true
  validate :engines_presence
  belongs_to :brand
  has_and_belongs_to_many :engines
  has_one :document, dependent: :destroy

  private

  def engines_presence
    errors.add(:base, 'Must have at least one engine available') if engines.empty?
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  include Authorization
  before_action :set_car, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :authorize_admin!, except: [:index, :show]

  # GET /cars or /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1 or /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars or /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to car_url(@car), notice: "Car was successfully created." }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1 or /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to car_url(@car), notice: "Car was successfully updated." }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1 or /cars/1.json
  def destroy
    @car.destroy

    respond_to do |format|
      format.html { redirect_to cars_url, notice: "Car was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_car
    @car = Car.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def car_params
    params.require(:car).permit(:brand_id, :model, :engine_ids => [])
  end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_car.html.erb
<div id="<%= dom_id car %>">
  <p>
    <strong>Brand:</strong>
    <%= car.brand_id %>
  </p>

  <p>
    <strong>Model:</strong>
    <%= car.model %>
  </p>

</div>

app/views/cars/_form.html.erb
<%= form_with(model: car) do |form| %>
  <% if car.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
        <% car.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :brand_id, style: "display: block" %>
    <%= form.text_field :brand_id %>
  </div>

  <div>
    <%= form.label :model, style: "display: block" %>
    <%= form.text_field :model %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
            crossorigin="anonymous"
        />
        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
            crossorigin="anonymous"
        ></script>
    </head>
    <body class="bg-dark-subtle min-vh-100 d-flex flex-column">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid justify-content-start">
                <button
                    class="navbar-toggler"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarNav"
                    aria-controls="navbarNav"
                    aria-expanded="false"
                    aria-label="Toggle navigation"
                >
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand ps-4" href="#">T5</a>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <% if current_user %>
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="<%= brands_path %>">Brands</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<%= cars_path %>">Cars</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<%= engines_path %>">Engines</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<%= documents_path %>">Documents</a>
                            </li>
                            <%= button_to(
                                "Log Out",
                                destroy_user_session_path,
                                method: :delete,
                                class:  "nav-link"
                            ) %>
                        <% else %>
                            <li class="nav-item">
                                <a class="nav-link" href="<%= new_user_session_path %>">Sign in</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<%= new_user_registration_path %>">Sign up</a>
                            </li>
                        <% end %>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container d-flex flex-column flex-grow-1 align-items-center justify-content-center">
            <h1>Editing car</h1>
            <p id="car-help" class="text-decoration-underline mb-1">Help<p>
            <%= form_with(model: @car, html: { class: 'bg-dark rounded-4 text-white p-4 justify-content-center text-center' }) do |form| %>
                <div class="mb-3">
                    <%= form.label :model, class: 'form-label', style: "display: block" %>
                    <%= form.text_field :model, class: 'form-control' %>
                </div>

                <div class="mb-3">
                    <%= form.label :brand_id, class: 'form-label', style: "display: block" %>
                    <%= form.collection_select :brand_id, Brand.all, :id, :name, {}, class: 'form-select' %>
                </div>

                <div class="mb-3 text-start">
                    <div>
                        <%= form.label :engine_ids, "Available engines :", class:'mb-3', style: "display: block" %>
                        <% Engine.all.each do |engine| %>
                        <div class="form-check">
                            <%= form.check_box :engine_ids, { multiple: true, class:'form-check-input' }, engine.id, nil  %>
                            <%= form.label :engine_ids, engine.code, class: 'form-check-label' %>
                        </div>
                        <% end %>
                    </div>
                </div>

                <div>
                    <%= form.submit "Edit car", class: 'btn btn-warning' %>
                </div>
                <% if @car.errors.any? %>
                    <div class="mt-3">
                        <% @car.errors.full_messages.each do |message| %>
                            <span class="text-danger"><%= message %></span><br />
                        <% end %>
                    </div>
                <% end %>
            <% end %>
            <a class="mt-3" href="<%= car_path(@car) %>">Return to car</a>
        </div>

        <script>
            var helpCarButton = document.getElementById('car-help');
            helpCarButton.addEventListener('click', function() {
            alert("Fill in the fields with the car model, the brand to which it belongs and the engines available in its range (if there is no option for brands or engines, it is because none have been created in the database yet).");
            });
        </script>
    </body>
</html>

app/views/cars/index.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
            crossorigin="anonymous"
        />

        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
            crossorigin="anonymous"
        ></script>
    </head>
    <body class="bg-dark-subtle min-vh-100 d-flex flex-column">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid justify-content-start">
                <button
                    class="navbar-toggler"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarNav"
                    aria-controls="navbarNav"
                    aria-expanded="false"
                    aria-label="Toggle navigation"
                >
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand ps-4" href="#">T5</a>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <% if current_user %>
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="<%= brands_path %>">Brands</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" href="<%= cars_path %>">Cars</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<%= engines_path %>">Engines</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<%= documents_path %>">Documents</a>
                            </li>
                            <%= button_to(
                                "Log Out",
                                destroy_user_session_path,
                                method: :delete,
                                class:  "nav-link"
                            ) %>
                        <% else %>
                            <li class="nav-item">
                                <a class="nav-link" href="<%= new_user_session_path %>">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<%= new_user_registration_path %>">Signup</a>
                            </li>
                        <% end %>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container d-flex flex-column flex-grow-1 align-items-center justify-content-center">
            <% if @cars.any? %>
            <h1>Your cars</h1>
            <table class="table my-4 rounded-4 table-dark overflow-hidden text-center">
                <thead>
                    <tr>
                        <th scope="col">Car</th>
                        <th scope="col">View</th>
                        <% if current_user.admin? %>
                            <th scope="col">Edit</th>
                            <th scope="col">Delete</th>
                        <% end %>
                    </tr>
                </thead>
                <tbody>
                    <% @cars.each do |car| %>
                        <tr>
                            <td><%= car.model %></td>
                            <td>
                                <a href="<%=car_path(car)%>" class="btn btn-primary">
                                    <svg
                                        xmlns="http://www.w3.org/2000/svg"
                                        width="16"
                                        height="16"
                                        fill="currentColor"
                                        class="bi bi-eye-fill"
                                        viewBox="0 0 16 16"
                                    >
                                        <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z" />
                                        <path d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z" />
                                    </svg>
                                </a>
                            </td>
                            <% if current_user.admin? %>
                                <td>
                                    <a href="<%=edit_car_path(car)%>" class="btn btn-warning">
                                        <svg
                                            xmlns="http://www.w3.org/2000/svg"
                                            width="16"
                                            height="16"
                                            fill="currentColor"
                                            class="bi bi-pencil-fill"
                                            viewBox="0 0 16 16"
                                        >
                                            <path
                                                d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"
                                            />
                                        </svg>
                                    </a>
                                </td>
                                <td>
                                    <%= button_to car_path(car), method: :delete, data: { confirm: "Are you sure you want to delete this car?" }, class: "btn btn-danger" do %>
                                        <svg
                                            xmlns="http://www.w3.org/2000/svg"
                                            width="16"
                                            height="16"
                                            fill="currentColor"
                                            class="bi bi-trash3-fill"
                                            viewBox="0 0 16 16"
                                        >
                                            <path
                                                d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5Zm-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5ZM4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06Zm6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528ZM8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5Z"
                                            />
                                        </svg>
                                    <% end %>
                                </td>
                            <% end %>
                        </tr>
                    <% end %>
                </tbody>
            </table>
            <% else %>
                <h1 class="text-center">No cars found</h1>
            <% end %>
            <%
                if current_user.admin?
                    %>
                        <a href="<%= new_car_path %>" class="btn btn-primary">Add new car</a>
                    <%
                end
            %>
        </div>
    </body>
</html>

app/views/cars/new.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
            crossorigin="anonymous"
        />
        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
            crossorigin="anonymous"
        ></script>
    </head>
    <body class="bg-dark-subtle min-vh-100 d-flex flex-column">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid justify-content-start">
                <button
                    class="navbar-toggler"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarNav"
                    aria-controls="navbarNav"
                    aria-expanded="false"
                    aria-label="Toggle navigation"
                >
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand ps-4" href="#">T5</a>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <% if current_user %>
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="<%= brands_path %>">Brands</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<%= cars_path %>">Cars</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<%= engines_path %>">Engines</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<%= documents_path %>">Documents</a>
                            </li>
                            <%= button_to(
                                "Log Out",
                                destroy_user_session_path,
                                method: :delete,
                                class:  "nav-link"
                            ) %>
                        <% else %>
                            <li class="nav-item">
                                <a class="nav-link" href="<%= new_user_session_path %>">Sign in</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<%= new_user_registration_path %>">Sign up</a>
                            </li>
                        <% end %>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container d-flex flex-column flex-grow-1 align-items-center justify-content-center">
            <h1>New car</h1>
            <p id="car-help" class="text-decoration-underline mb-1">Help<p>
            <%= form_with(model: @car, html: { class: 'bg-dark rounded-4 text-white p-4 justify-content-center text-center' }) do |form| %>
                <div class="mb-3">
                    <%= form.label :model, class: 'form-label', style: "display: block" %>
                    <%= form.text_field :model, class: 'form-control' %>
                </div>

                <div class="mb-3">
                    <%= form.label :brand_id, class: 'form-label', style: "display: block" %>
                    <%= form.collection_select :brand_id, Brand.all, :id, :name, {}, class: 'form-select' %>
                </div>

                <div class="mb-3 text-start">
                    <div>
                        <%= form.label :engine_ids, "Available engines :", class:'mb-3', style: "display: block" %>
                        <% Engine.all.each do |engine| %>
                        <div class="form-check">
                            <%= form.check_box :engine_ids, { multiple: true, class:'form-check-input' }, engine.id, nil  %>
                            <%= form.label :engine_ids, engine.code, class: 'form-check-label' %>
                        </div>
                        <% end %>
                    </div>
                </div>

                <div>
                    <%= form.submit "Create car", class: 'btn btn-primary' %>
                </div>
                <% if @car.errors.any? %>
                    <div class="mt-3">
                        <% @car.errors.full_messages.each do |message| %>
                            <span class="text-danger"><%= message %></span><br />
                        <% end %>
                    </div>
                <% end %>
            <% end %>
        </div>

        <script>
            var helpCarButton = document.getElementById('car-help');
            helpCarButton.addEventListener('click', function() {
            alert("Fill in the fields with the car model, the brand to which it belongs and the engines available in its range (if there is no option for brands or engines, it is because none have been created in the database yet).");
            });
        </script>
    </body>
</html>

app/views/cars/show.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
            crossorigin="anonymous"
        />

        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
            crossorigin="anonymous"
        ></script>
    </head>
    <body class="bg-dark-subtle min-vh-100 d-flex flex-column">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid justify-content-start">
                <button
                    class="navbar-toggler"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarNav"
                    aria-controls="navbarNav"
                    aria-expanded="false"
                    aria-label="Toggle navigation"
                >
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand ps-4" href="#">T5</a>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <% if current_user %>
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="<%= brands_path %>">Brands</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<%= cars_path %>">Cars</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<%= engines_path %>">Engines</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<%= documents_path %>">Documents</a>
                            </li>
                            <%= button_to(
                                "Log Out",
                                destroy_user_session_path,
                                method: :delete,
                                class:  "nav-link"
                            ) %>
                        <% else %>
                            <li class="nav-item">
                                <a class="nav-link" href="<%= new_user_session_path %>">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<%= new_user_registration_path %>">Signup</a>
                            </li>
                        <% end %>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container d-flex flex-column flex-grow-1 align-items-center justify-content-center">
            <h1>Car <%= @car.model %></h1>
            <table class="table my-4 rounded-4 table-dark overflow-hidden text-center">
                <thead>
                    <tr>
                        <th scope="col">Model</th>
                        <th scope="col">Brand</th>
                        <th scope="col">Available engines</th>
                        <th scope="col">Document</th>
                        <% if current_user.admin? %>
                            <th scope="col">Edit</th>
                            <th scope="col">Delete</th>
                        <% end %>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><%= @car.model %></td>
                        <td><%= link_to @car.brand.name, brand_path(@car.brand) %></td>
                        <td>
                            <% @car.engines.each do |engine| %>
                                <%= link_to engine.code, engine_path(engine) %><br />
                            <% end %>
                        </td>
                        <td><% if @car.document %><%= link_to @car.document.code, document_path(@car.document) %><% end %></td>
                        <% if current_user.admin? %>
                            <td>
                                <a href="<%=edit_car_path(@car)%>" class="btn btn-warning">
                                    <svg
                                        xmlns="http://www.w3.org/2000/svg"
                                        width="16"
                                        height="16"
                                        fill="currentColor"
                                        class="bi bi-pencil-fill"
                                        viewBox="0 0 16 16"
                                    >
                                        <path
                                            d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"
                                        />
                                    </svg>
                                </a>
                            </td>
                            <td>
                                <%= button_to car_path(@car), method: :delete, data: { confirm: "Are you sure you want to delete this car?" }, class: "btn btn-danger" do %>
                                    <svg
                                        xmlns="http://www.w3.org/2000/svg"
                                        width="16"
                                        height="16"
                                        fill="currentColor"
                                        class="bi bi-trash3-fill"
                                        viewBox="0 0 16 16"
                                    >
                                        <path
                                            d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5Zm-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5ZM4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06Zm6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528ZM8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5Z"
                                        />
                                    </svg>
                                <% end %>
                            </td>
                        <% end %>
                    </tr>
                </tbody>
            </table>
        </div>
    </body>
</html>